### ISSUE TITLE
Feature detection

### ISSUE THREAD

**Issue by ahudson87** [fixstream-web/website#6]
Implement [modernizr](https://modernizr.com/docs) (or comparable). Needs to be configurable in source and integrate into JS compiler (into `head.js`).

Should be able to add/remove specifics tests on the fly. Specific tests not important at this time.

**Comment by jesseaborden** [comment]
@ahudson87, did you have preference on where you wanted this configured? We can use this to put include it at the webpack level: https://www.npmjs.com/package/modernizr-webpack-plugin or we can use this one to add it to the head.js source code directly: https://www.npmjs.com/package/modernizr. Both look like they will do the trick.

**Comment by ahudson87** [comment]
thanks @jesseaborden - I might go with [https://www.npmjs.com/package/modernizr](https://www.npmjs.com/package/modernizr) based mainly on package maturity & popularity. But if you think that the alternative offers a significantly more straight-forward implementation, I could be convinced.

**Comment by jesseaborden** [comment]
@ahudson87 Sounds good. I'll pop that in now.

**Comment by ahudson87** [comment]
@jesseaborden thanks again- closing this out.
